### ISSUE TITLE
Special characters throw exception

### ISSUE THREAD

**Issue by Im-Sue** [astraw/svg_stack#16]
exception content : 

`Traceback (most recent call last):
  File "/dat/svgStack/svg_stack.py", line 713, in <module>
    main()
  File "/dat/svgStack/svg_stack.py", line 706, in main
    layout.addSVG(fname,alignment=AlignCenter)
  File "/dat/svgStack/svg_stack.py", line 632, in addSVG
    svg_file = SVGFile(svg_file)
  File "/dat/svgStack/svg_stack.py", line 177, in __init__
    self._root = etree.parse(fname).getroot()
  File "lxml.etree.pyx", line 3197, in lxml.etree.parse (src/lxml/lxml.etree.c:64816)
  File "parser.pxi", line 1571, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:92729)
  File "parser.pxi", line 1600, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:93013)
  File "parser.pxi", line 1500, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:92076)
  File "parser.pxi", line 1047, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:88976)
  File "parser.pxi", line 577, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:84385)
  File "parser.pxi", line 676, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:85488)
  File "parser.pxi", line 616, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:84811)
lxml.etree.XMLSyntaxError: PCDATA invalid Char value 3, line 565, column 70
`

exception Svg fragment：
`<text alignment-baseline="auto" font-size="14" style="" x="843.5224609375" y="13.02" ></text>`

**Comment by astraw** [comment]
Thanks for the report. This looks like an error from lxml which will be difficult for us to fix. Nevertheless, can you upload a complete svg file that elicits the problem?
